package i18n

var english = map[string]string{
	"help.usage":    "Usage of gommit:",
	"ai.generating": "Gemini is analyzing the staged changes...", "ai.generated": "AI suggestion: %s: %s", "ai.failed": "AI commit generation failed: %v", "ai.invalid_type": "Gemini returned an unsupported commit type: %s", "type.AI": "Auto commit with Gemini (type + subject)",
	"help.version": "print version and exit", "help.install": "install this binary into your user bin and exit", "help.update": "download and install the latest GitHub release", "help.dry_run": "print the message and exit (do not run git commit)", "help.mode": "prompt mode for this run: simple or full", "help.set_mode": "save the default prompt mode globally: simple or full", "help.language": "interface language for this run: en, es, pt, hi, ru or zh", "help.set_language": "save the default interface language globally", "help.type": "commit type (feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert; extras: WIP, prune)", "help.scope": "optional scope (e.g. ui, api, editor)", "help.subject": "commit subject (imperative, <=72 chars)", "help.body": "commit body (use \\n for new lines)", "help.footer": "commit footer (e.g. Closes #123; BREAKING CHANGE: ...)", "help.editor": "run as Git editor (writes COMMIT_EDITMSG)", "help.allow_empty": "allow an empty commit", "help.amend": "amend the previous commit", "help.no_verify": "bypass pre-commit and commit-msg hooks", "help.signoff": "add Signed-off-by trailer", "help.auto_stage": "auto stage all changes when nothing is staged", "help.show_status": "print staged changes before committing",
	"language.saved": "Default language saved: %s", "language.invalid": "invalid language %q (use %s)", "mode.saved": "Default mode saved: %s", "mode.invalid": "invalid mode %q (use simple or full)",
	"menu.interactive": "Select the type (↑/↓ to move, Enter to select, q to quit):", "menu.title": "Select the type of change (use number, type name, or search):", "menu.hint": "Type a number, commit type, search term, or 'q' to quit", "menu.prompt": "? Select the type of change you're committing: ", "menu.multiple": "Multiple matches found. Please be more specific:", "menu.invalid": "Invalid selection:", "menu.retry": "Please try again.", "menu.continue": "Press Enter to continue...",
	"prompt.scope": "Scope (optional, Enter to skip): ", "prompt.subject": "Subject (required, imperative, <=72 chars): ", "prompt.description": "Describe the change (required, <=72 chars): ", "prompt.body": "Body (optional, multiline). Finish with '.' on a new line, or press Enter twice:", "prompt.breaking": "Are there any breaking changes?", "prompt.breaking_desc": "Describe the breaking change: ", "prompt.issues": "Does this change affect any open issues?", "prompt.closes": "Issues to close (comma, e.g. 12,45) — Enter to skip: ", "prompt.refs": "Issues to reference (comma, e.g. 7,9) — Enter to skip: ",
	"preview": "Commit message preview:", "staged": "Staged changes:", "autostage": "No staged changes detected. Running: git add -A", "amend.last": "Amend mode: last commit → %s", "amend.update": "Amend mode: last commit will be updated.", "update.notice": "\n⬆ Gommit %s is available (current: %s). Run: gommit --update", "update.current": "Gommit is already up to date (%s).", "update.downloaded": "Gommit %s downloaded. Finishing installation...",
	"type.WIP": "Work in progress", "type.feat": "A new feature", "type.fix": "Fixing a bug", "type.chore": "Dependencies, deployments, or configuration", "type.refactor": "Improving code structure", "type.prune": "Removing code or files", "type.docs": "Writing documentation", "type.perf": "Improving performance", "type.test": "Adding tests", "type.build": "Build system or dependencies", "type.ci": "CI/CD configuration", "type.style": "Changes that do not affect code meaning", "type.revert": "Revert a commit",
}
